<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
  $('#collapseFilterForm').on('shown', function() {
    var icon = $('.filterFormHeading i', $(this).parent());
    icon.removeClass('icon-chevron-down');
    icon.addClass('icon-chevron-up');
  });
  $('#collapseFilterForm').on('hidden', function() {
    var icon = $('.filterFormHeading i', $(this).parent());
    icon.removeClass('icon-chevron-up');
    icon.addClass('icon-chevron-down');
  });
});
<?php $this->headScript()->captureEnd() ?>
<h2><?php echo $this->pageTitle ?></h2>
<?php if ($this->filterForm): ?>
  <div class="accordion">
    <div class="accordion-group well" style="padding: 0px">
      <div class="accordion-heading filterFormHeading">
        <a class="btn accordion-toggle" data-toggle="collapse" href="#collapseFilterForm"><i class="icon-chevron-down"></i></a>
      </div>
      <div id="collapseFilterForm" class="accordion-body collapse">
        <div class="accordion-inner">
          <?php echo $this->filterForm->setAttrib('style', 'margin-bottom: 0px'); ?>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <?php foreach ($this->keys as $key): ?>
        <th>
          <a href="<?php echo $this->url(array('order' => $this->nextOrder, 'sort' => $key)) ?>">
            <?php if ($key === $this->currentSort): ?>
              <i class="<?php echo (strtolower($this->nextOrder) == 'asc' ? 'icon-chevron-down' : 'icon-chevron-up') ?>"></i>
            <?php endif; ?>
            <?php echo $key ?>
          </a>
        </th>
      <?php endforeach ?>
      <th><?php echo $this->translate('Crud/Methods') ?></th>
    </tr>
  </thead>
  <tbody>
  <?php $i = 1; ?>
  <?php foreach ($this->paginator as $record): ?>
    <tr class="<?php echo ($i++ & 1 ? 'odd' : 'even') ?>">
      <?php foreach ($this->keys as $key): ?>
        <td>
        <?php
//        var_dump($record->getId());
        $field = $record[$key];
        if (is_bool($field)) {
          echo $field ? $this->translate('Crud/True') : $this->translate('Crud/False');
        } elseif ($field instanceof DateTime) {
          $date = new Zend_Date($field->getTimestamp());
          echo $date->toString();
        } elseif (is_object($field)) {
          echo (string)$field;
        }
        else {
          echo $field;
        }
        ?>
        </td>
      <?php endforeach ?>
      <td class="methods">
        <a class="btn btn-small" title="<?php echo $this->translate('Crud/Update/Label') ?>" href="<?php echo $this->url(array('action' => 'update', 'id' => $record->getId())) ?>"><i class="icon-edit"></i></a>
        &nbsp;<a class="btn btn-danger btn-small" title="<?php echo $this->translate('Crud/Delete/Label') ?>" onclick="javascript: return confirm('<?php echo $this->translate('Crud/Delete/Confirm')?>')" href="<?php echo $this->url(array('action' => 'delete', 'id' => $record->getId())) ?>"><i class="icon-trash icon-white"></i></a>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginationBootstrap.phtml'); ?>