<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
  $('#collapseFilterForm').on('shown', function() {
    var icon = $('.filterFormHeading i', $(this).parent());
    icon.removeClass('icon-chevron-down');
    icon.addClass('icon-chevron-up');
  });
  $('#collapseFilterForm').on('hidden', function() {
    var icon = $('.filterFormHeading i', $(this).parent());
    icon.removeClass('icon-chevron-up');
    icon.addClass('icon-chevron-down');
  });
});
<?php $this->headScript()->captureEnd() ?>
<?php if ($this->filterForm): ?>
  <div class="accordion">
    <div class="accordion-group well" style="padding: 0px">
      <div class="accordion-heading filterFormHeading">
        <a class="btn accordion-toggle" data-toggle="collapse" href="#collapseFilterForm" style="text-align: left; padding-left: 10px;">
          <i class="icon-chevron-down"></i> <?php echo $this->translate('Crud/Filter')?>
        </a>
      </div>
      <div id="collapseFilterForm" class="accordion-body collapse">
        <div class="accordion-inner">
          <?php echo $this->filterForm->setAttrib('style', 'margin-bottom: 0px'); ?>
        </div>
      </div>
    </div>
  </div>
<?php endif ?>
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <?php foreach ($this->keys as $key): ?>
        <th>
          <a href="<?php echo $this->url(array('order' => $this->nextOrder, 'sort' => $key)) ?>">
            <?php if ($key === $this->currentSort): ?>
              <i class="<?php echo (strtolower($this->nextOrder) == 'asc' ? 'icon-chevron-down' : 'icon-chevron-up') ?>"></i>
            <?php endif; ?>
            <?php if ($this->translate()->getTranslator()->isTranslated($this->headerKeyPrefix . $key)): ?>
              <?php echo $this->translate($this->headerKeyPrefix . $key) ?>
            <?php else: ?>
              <?php echo $key ?>
            <?php endif ?>
          </a>
        </th>
      <?php endforeach ?>
      <th><?php echo $this->translate('Crud/Methods') ?></th>
    </tr>
  </thead>
  <tbody>
  <?php $i = 1; ?>
  <?php foreach ($this->paginator as $record): ?>
    <tr class="<?php echo ($i++ & 1 ? 'odd' : 'even') ?>">
      <?php foreach ($this->keys as $key): ?>
        <td>
        <?php
        $field = $record[$key];
        if (is_bool($field)) {
          echo $field ? $this->translate('Crud/True') : $this->translate('Crud/False');
        } elseif ($field instanceof DateTime) {
          $date = new Zend_Date($field->getTimestamp());
          echo $date->toString();
        } else {
          echo $this->escape((string)$field);
        }
        ?>
        </td>
      <?php endforeach ?>
      <td class="methods">
        <div class="btn-group">
          <a class="btn"
             title="<?php echo $this->translate('Crud/Update/Label') ?>"
             href="<?php echo $this->url(array('action' => 'update', 'id' => $record->getId())) ?>">
            <i class="icon-pencil"></i>
          </a>
          <a class="btn btn-danger"
             title="<?php echo $this->translate('Crud/Delete/Label') ?>"
             onclick="javascript: return confirm('<?php echo $this->translate('Crud/Delete/Confirm')?>')"
             href="<?php echo $this->url(array('action' => 'delete', 'id' => $record->getId())) ?>">
            <i class="icon-trash icon-white"></i>
          </a>
        </div>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginationBootstrap.phtml'); ?>