<div class="messages">
<?php
  if (isset($this->messageTypes) && count($this->messageTypes) > 0) {
    foreach ($this->messageTypes as $type => $messages) { ?>
      <div class="alert alert-<?php echo $type ?> fade in">
        <a class="close" data-dismiss="alert">×</a>
        <?php foreach ($messages as $message): ?>
          <?php echo $this->translate($message) ?><br />
        <?php endforeach ?>
      </div>
    <?php }
  } ?>
</div>